import {
	AlertTriangle,
	ArrowRight,
	Check,
	ChevronLeft,
	ChevronRight,
	CircuitBoardIcon,
	Command,
	CreditCard,
	File,
	FileText,
	HelpCircle,
	Image,
	Laptop,
	LayoutDashboardIcon,
	Loader2,
	LogIn,
	LucideIcon,
	Moon,
	MoreVertical,
	Pizza,
	Plus,
	Settings,
	SunMedium,
	Trash,
	User,
	User2Icon,
	UserX2Icon,
	X
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
	dashboard: LayoutDashboardIcon,
	logo: Command,
	login: LogIn,
	close: X,
	profile: User2Icon,
	spinner: Loader2,
	kanban: CircuitBoardIcon,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	trash: Trash,
	employee: UserX2Icon,
	post: FileText,
	page: File,
	media: Image,
	settings: Settings,
	billing: CreditCard,
	ellipsis: MoreVertical,
	add: Plus,
	warning: AlertTriangle,
	user: User,
	arrowRight: ArrowRight,
	help: HelpCircle,
	pizza: Pizza,
	sun: SunMedium,
	moon: Moon,
	laptop: Laptop,
	check: Check
};
